### PR TITLE
Turn-taking bot

### PR DESCRIPTION
**Pull request by atuefekci**
The turn-taking bot realizes a controlled dialogue flow between two users.
Necessary data is read from the example file `questions_images.json`.

For the bot to **work properly** you will have to set the plugin triggers (both in the `waiting_room.json` and in the `meetup_task.json`) as follows:

`"submit-message"`: `"intercept-message"`
`"print-history"`: `"intercept-history"`

### CODE REVIEW

**Comment by TimDiekmann** [comment]
Nice work! 
Was this designed to be a sample bot or as bot for a specific project? We want to keep the bots in the repository as small as possible and probably completely remove all sample bot and move them to external repositories as mentioned in #45 and only link them in the *README.md* and the documentation.

**Comment by TimDiekmann** [comment]
I guess, @davidschlangen likes to see interceptions in action? Here you go! 🙂

**Comment by davidschlangen** [comment]
Good stuff!

This is meant to be a sample bot. It’s a fine line, but I think this kind of abstract skeleton bot should indeed be bundled with the main code. 

Which reminds me, I’m not exactly clear what the role of the mentioned plugin trigger jsons is, but whatever it is, the file should not be called meetup_task.json. The term „meet-up“ should not occur anywhere, in fact, as this is a concrete instantiation in a particular game (which has nothing to do with this one).

**Comment by davidschlangen** [comment]
-Makes sense! (Putting both into a directory.) `questions_images.json` is only used there, as far as I know.

**Pull request merged**
